
package slenduhhova.myfitty;

import java.util.ArrayList;
import javax.swing.JLabel;
import slenduhhova.myfitty.dataaccess.DataAccess;
import slenduhhova.myfitty.dto.Usuari;

/**
 *
 * @author annas
 */
public class MainAfterLogin extends javax.swing.JPanel {

    /**
     * Creates new form MainAfterLogin
     */
    
    Main main;
    
    public MainAfterLogin(Main main) {
        this.main=main;
        initComponents(); 
        setSize(400,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcomeNameOfInstructor = new javax.swing.JLabel();
        jButtonShowListOfUsers = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShowInfoUsers = new javax.swing.JTextArea();

        setAlignmentX(0.0F);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(320, 350));

        jLabelWelcomeNameOfInstructor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelWelcomeNameOfInstructor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcomeNameOfInstructor.setToolTipText("");
        jLabelWelcomeNameOfInstructor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonShowListOfUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonShowListOfUsers.setText("Show all users");
        jButtonShowListOfUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowListOfUsersActionPerformed(evt);
            }
        });

        jTextAreaShowInfoUsers.setColumns(20);
        jTextAreaShowInfoUsers.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShowInfoUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonShowListOfUsers))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelWelcomeNameOfInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelWelcomeNameOfInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowListOfUsers)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowListOfUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowListOfUsersActionPerformed
        DataAccess da = new DataAccess();
        ArrayList<Usuari> usuaris = da.getAllUsers();
        jTextAreaShowInfoUsers.removeAll();
        for(Usuari u: usuaris){
            jTextAreaShowInfoUsers.append(u.getId() + " " + u.getNom() + " " + u.getEmail() + " " 
            + u.getPasswordHash().substring(0,5) + " " + "\n");}
    }//GEN-LAST:event_jButtonShowListOfUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShowListOfUsers;
    private javax.swing.JLabel jLabelWelcomeNameOfInstructor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaShowInfoUsers;
    // End of variables declaration//GEN-END:variables



    public javax.swing.JLabel getjLabelWelcomeNameOfInstructor() {
        return jLabelWelcomeNameOfInstructor;
    }

    public void setjLabelWelcomeNameOfInstructor(javax.swing.JLabel jLabelWelcomeNameOfInstructor) {
        this.jLabelWelcomeNameOfInstructor = jLabelWelcomeNameOfInstructor;
    }
}
