/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package slenduhhova.myfitty;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author annas
 */
public class MainBeforeLogin extends javax.swing.JPanel {
    
    Main main;

    /**
     * Creates new form MainBeforeLogin
     * @param main
     */
    public MainBeforeLogin(Main main) {
        this.main=main;
        initComponents();
        setSize(400,450);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIcon = new javax.swing.JLabel();
        jLabelHyperlink = new javax.swing.JLabel();
        jButtonGoToLoginDialog = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setPreferredSize(new java.awt.Dimension(320, 350));

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono.png"))); // NOI18N

        jLabelHyperlink.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHyperlink.setText("www.fitty.com");
        jLabelHyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHyperlinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHyperlinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHyperlinkMouseExited(evt);
            }
        });

        jButtonGoToLoginDialog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonGoToLoginDialog.setText("LOGIN");
        jButtonGoToLoginDialog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGoToLoginDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoToLoginDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabelHyperlink))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonGoToLoginDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHyperlink)
                .addGap(33, 33, 33)
                .addComponent(jButtonGoToLoginDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoToLoginDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoToLoginDialogActionPerformed
        Login login = new Login(main);
        login.setVisible(true);
    }//GEN-LAST:event_jButtonGoToLoginDialogActionPerformed

    private void jLabelHyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHyperlinkMouseClicked
        try {
        Desktop.getDesktop().browse(new URL("https://paucasesnovescifp.cat/").toURI());
        }
        catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_jLabelHyperlinkMouseClicked

    private void jLabelHyperlinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHyperlinkMouseEntered
        jLabelHyperlink.setText("<html><a href='' style=\"color:#FF4500;\">" + jLabelHyperlink.getText() + "</a></html>");
    }//GEN-LAST:event_jLabelHyperlinkMouseEntered

    private void jLabelHyperlinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHyperlinkMouseExited
        jLabelHyperlink.setText("www.fitty.com");
    }//GEN-LAST:event_jLabelHyperlinkMouseExited
                                        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGoToLoginDialog;
    private javax.swing.JLabel jLabelHyperlink;
    private javax.swing.JLabel jLabelIcon;
    // End of variables declaration//GEN-END:variables
}
